version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: election_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: election_db
      MYSQL_USER: election_user
      MYSQL_PASSWORD: Password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - election-network

volumes:
  db_data:

networks:
  election-network:
    driver: bridge
